language: java
cache:
  directories:
    - $HOME/.gradle
    - .gradle
sudo: false
before_install:
  - git submodule update --init --recursive
  - chmod a+x gradlew
notifications:
 irc:
  channels:
   - "irc.esper.net#BBM-bots"
  template:
   - "%{build_number} (%{branch} - %{commit}: %{commit_message} : %{author}): %{message} (%{build_url})"
install: true
script:
  - ./gradlew build -PbambooshortPlanName=VoltzEngine -Pdmodcurse=61545 --refresh-dependencies
jdk:
  - oraclejdk7
  - oraclejdk8